### PR TITLE
More message types

### PR DESCRIPTION
**Pull request by barrucadu**
One type for every sort of message, with the encoding and decoding logic unified in one place.

CC @zimbatm

### CODE REVIEW

**Comment by barrucadu** [comment]
Travis appears to be having problems.

**Comment by zimbatm** [comment]
What do you mean by "More message types" in the last method?

**Comment by barrucadu** [comment]
Have a separate type for each sort of message, rather than one type for all messages + ad-hoc marshalling and unmarshalling elsewhere in the code.

**Comment by zimbatm** [comment]
Oh I see. I don't have any problems with the implementation, it looks sound to me.

**Comment by barrucadu** [comment]
Good to merge, then?

**Comment by zimbatm** [comment]
Regarding travis, it looks justified. Did you run `go test ./encoding`?

**Comment by barrucadu** [comment]
Fixed now.

**Comment by zimbatm** [comment]
I think it's because it's trying to use the vendor/ repo. In the logs there is this queue: "Using Go 1.5 Vendoring, not checking for Godeps"

**Comment by barrucadu** [comment]
Do I need to fix that, or is it ok to leave it?

**Comment by zimbatm** [comment]
It's nice if you can. But since it's already broken in master it's not a responsibility of this PR.

**Pull request merged**
